# Generated by Django 3.2.16 on 2024-01-10 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_folow_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folow',
            new_name='Follow',
        ),
    ]
